In [1]:
import tensorflow as tf

from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding, LSTM, Dense, Bidirectional
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
import numpy as np 

In [8]:
tokenizer = Tokenizer()

data = open('dataset2.txt').read()

corpus = data.lower().split("<eos>")

#print(corpus)

tokenizer.fit_on_texts(corpus)
total_words = len(tokenizer.word_index) + 1

#print(tokenizer.word_index)
#print(total_words)


In [9]:
input_sequences = []
# input_sequences = []
# i = 1
# for line in corpus:
#     if i>=1 && i <=12 :
#         stanza = tokenizer.texts_to_sequences([line])[0]    
#     else:
        
#     i = i%14

for line in corpus:
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        n_gram_sequence = token_list[:i+1]
        input_sequences.append(n_gram_sequence)

# pad sequences 
max_sequence_len = max([len(x) for x in input_sequences])
input_sequences = np.array(pad_sequences(input_sequences, maxlen=max_sequence_len, padding='pre'))

# create predictors and label
xs, labels = input_sequences[:,:-1],input_sequences[:,-1]

ys = tf.keras.utils.to_categorical(labels, num_classes=total_words)

In [12]:
print(xs[6])

[   0    0    0    0    0    0    0   96  105  650   54 1826   34    7]


In [13]:
print(ys[6])

[0. 0. 0. ... 0. 0. 0.]


In [14]:
print(xs[5])
print(ys[5])

[   0    0    0    0    0    0    0    0   96  105  650   54 1826   34]
[0. 0. 0. ... 0. 0. 0.]


In [15]:
print(tokenizer.word_index)

{'the': 1, 'and': 2, 'of': 3, 'to': 4, 'in': 5, 'a': 6, 'that': 7, 'i': 8, 'with': 9, 'my': 10, "'s": 11, 'his': 12, 'all': 13, 'for': 14, 'but': 15, 'from': 16, 'her': 17, 'thy': 18, 'is': 19, 'as': 20, 'on': 21, "'d": 22, 'he': 23, 'me': 24, 'not': 25, 'their': 26, 'so': 27, 'this': 28, 'by': 29, 'love': 30, 'thou': 31, 'or': 32, 'be': 33, 'it': 34, '—': 35, 'yet': 36, 'when': 37, 'they': 38, 'we': 39, 'no': 40, 'like': 41, '’': 42, 'which': 43, 'our': 44, 'at': 45, 'you': 46, 'are': 47, 'was': 48, 'if': 49, 'she': 50, 'then': 51, 'more': 52, '“': 53, 'what': 54, 'thee': 55, 'who': 56, 'have': 57, 'now': 58, 'heart': 59, 'nor': 60, 'one': 61, '‘': 62, 'some': 63, 'where': 64, 'your': 65, 'still': 66, 'shall': 67, 'may': 68, 'life': 69, 'will': 70, 'day': 71, 'there': 72, 'them': 73, 'eyes': 74, 'than': 75, 'did': 76, 'him': 77, 'o': 78, 'its': 79, 'soul': 80, 'can': 81, 'world': 82, 'these': 83, 'had': 84, 'whose': 85, 'thus': 86, 'see': 87, 'those': 88, 'time': 89, 'through': 90, 'm

In [16]:
model = Sequential()
model.add(Embedding(total_words, 100, input_length=max_sequence_len-1))
model.add(Bidirectional(LSTM(150)))
model.add(Dense(total_words, activation='softmax'))
adam = Adam(lr=0.01)
model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])
#earlystop = EarlyStopping(monitor='val_loss', min_delta=0, patience=5, verbose=0, mode='auto')
history = model.fit(xs, ys, epochs=100, verbose=1)
#print model.summary()
print(model)


Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/100
33802/33802 [==============================] - 71s 2ms/sample - loss: 7.3899 - acc: 0.0536
Epoch 2/100
33802/33802 [==============================] - 63s 2ms/sample - loss: 7.6170 - acc: 0.0569
Epoch 3/100
33802/33802 [==============================] - 64s 2ms/sample - loss: 7.3755 - acc: 0.0650
Epoch 4

33802/33802 [==============================] - 82s 2ms/sample - loss: 2.9022 - acc: 0.4454
Epoch 60/100
33802/33802 [==============================] - 75s 2ms/sample - loss: 2.9005 - acc: 0.4465
Epoch 61/100
33802/33802 [==============================] - 66s 2ms/sample - loss: 2.8436 - acc: 0.4514
Epoch 62/100
33802/33802 [==============================] - 80s 2ms/sample - loss: 2.7860 - acc: 0.4573
Epoch 63/100
33802/33802 [==============================] - 88s 3ms/sample - loss: 2.7711 - acc: 0.4604
Epoch 64/100
33802/33802 [==============================] - 73s 2ms/sample - loss: 2.8661 - acc: 0.4518
Epoch 65/100
33802/33802 [==============================] - 66s 2ms/sample - loss: 2.7966 - acc: 0.4582
Epoch 66/100
33802/33802 [==============================] - 76s 2ms/sample - loss: 2.7676 - acc: 0.4627
Epoch 67/100
33802/33802 [==============================] - 81s 2ms/sample - loss: 2.7838 - acc: 0.4622
Epoch 68/100
33802/33802 [==============================] - 77s 2ms/sample - 

In [19]:
import matplotlib.pyplot as plt


def plot_graphs(history, string):
  plt.plot(history.history[string])
  plt.xlabel("Epochs")
  plt.ylabel(string)
  plt.show()

In [20]:
#plot_graphs(history, 'accuracy')


In [43]:
# estimating 7 words per line => 7*13 = 91
seed_text = "The sky is bright and blue"
next_words = 91
  
for _ in range(next_words):
    token_list = tokenizer.texts_to_sequences([seed_text])[0]
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = model.predict_classes(token_list, verbose=0)
    output_word = ""
    for word, index in tokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    seed_text += " " + output_word


In [44]:
print(seed_text)

The sky is bright and blue infinity rome led near him woe 's own sphere weeps fraught garin mightie peeres souverain garin glade glade hurt exist fear glade case pretends scarred sphere gallantly fear wrack fear of fear revealed stroke garin force garin rosy chants fly advanced monarchies garin fear wrack fail crowns mended of alt'ring welle mi censura cidre expence weeps fraught nothingness ridge saith ridge sways fear monarch answered tous ces buveurs d'une hydre insight soaring wing enable tyrannies sweeps deprived women que yo persigo shared castles dan pail weeps souverain scarred sphere garin garin


In [46]:
seed_text = seed_text.split(" ")

In [47]:
i=0
for word in seed_text: 
    if i%7 == 0:
        print()
    if i%28==0:
        print()
    print(word, end = " ") 
    i = i+1
    



The sky is bright and blue infinity 
rome led near him woe 's own 
sphere weeps fraught garin mightie peeres souverain 
garin glade glade hurt exist fear glade 

case pretends scarred sphere gallantly fear wrack 
fear of fear revealed stroke garin force 
garin rosy chants fly advanced monarchies garin 
fear wrack fail crowns mended of alt'ring 

welle mi censura cidre expence weeps fraught 
nothingness ridge saith ridge sways fear monarch 
answered tous ces buveurs d'une hydre insight 
soaring wing enable tyrannies sweeps deprived women 

que yo persigo shared castles dan pail 
weeps souverain scarred sphere garin garin 